CREATE DATABASE IF NOT EXISTS raffle;
USE raffle;

CREATE TABLE IF NOT EXISTS tickets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prizes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  weight INT NOT NULL DEFAULT 1,
  quantity INT NOT NULL DEFAULT 1,
  image_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS prize_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prize_name VARCHAR(255) NOT NULL,
  ticket_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_config (
  config_key VARCHAR(255) PRIMARY KEY,
  config_value VARCHAR(255) NOT NULL
);

-- 2026-02-13: add columns to prize table
ALTER TABLE prizes ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE prizes ADD COLUMN price DECIMAL(10, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE prizes ADD COLUMN is_monetary TINYINT(1) NOT NULL DEFAULT 0;
