CREATE DATABASE IF NOT EXISTS raffle;
USE raffle;

CREATE TABLE IF NOT EXISTS tickets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prizes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  weight INT NOT NULL DEFAULT 1,
  quantity INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS prize_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prize_name VARCHAR(255) NOT NULL,
  ticket_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_config (
  config_key VARCHAR(255) PRIMARY KEY,
  config_value VARCHAR(255) NOT NULL
);
